// Generated by gencpp from file yolov3_pytorch_ros/xyrange.msg
// DO NOT EDIT!


#ifndef YOLOV3_PYTORCH_ROS_MESSAGE_XYRANGE_H
#define YOLOV3_PYTORCH_ROS_MESSAGE_XYRANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov3_pytorch_ros
{
template <class ContainerAllocator>
struct xyrange_
{
  typedef xyrange_<ContainerAllocator> Type;

  xyrange_()
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
    }
  xyrange_(const ContainerAllocator& _alloc)
    : xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
  (void)_alloc;
    }



   typedef uint16_t _xmin_type;
  _xmin_type xmin;

   typedef uint16_t _ymin_type;
  _ymin_type ymin;

   typedef uint16_t _xmax_type;
  _xmax_type xmax;

   typedef uint16_t _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> const> ConstPtr;

}; // struct xyrange_

typedef ::yolov3_pytorch_ros::xyrange_<std::allocator<void> > xyrange;

typedef boost::shared_ptr< ::yolov3_pytorch_ros::xyrange > xyrangePtr;
typedef boost::shared_ptr< ::yolov3_pytorch_ros::xyrange const> xyrangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yolov3_pytorch_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'yolov3_pytorch_ros': ['/home/sun/ros_ws/src/yolov3_pytorch_ros/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44036a17ac3e93c59e9c4fb4fbc536ff";
  }

  static const char* value(const ::yolov3_pytorch_ros::xyrange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44036a17ac3e93c5ULL;
  static const uint64_t static_value2 = 0x9e9c4fb4fbc536ffULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov3_pytorch_ros/xyrange";
  }

  static const char* value(const ::yolov3_pytorch_ros::xyrange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 xmin\n\
uint16 ymin\n\
uint16 xmax\n\
uint16 ymax\n\
\n\
\n\
";
  }

  static const char* value(const ::yolov3_pytorch_ros::xyrange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xyrange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov3_pytorch_ros::xyrange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov3_pytorch_ros::xyrange_<ContainerAllocator>& v)
  {
    s << indent << "xmin: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV3_PYTORCH_ROS_MESSAGE_XYRANGE_H
