// Generated by gencpp from file bin_msgs/Target.msg
// DO NOT EDIT!


#ifndef BIN_MSGS_MESSAGE_TARGET_H
#define BIN_MSGS_MESSAGE_TARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bin_msgs
{
template <class ContainerAllocator>
struct Target_
{
  typedef Target_<ContainerAllocator> Type;

  Target_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , type()  {
    }
  Target_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , type(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::bin_msgs::Target_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bin_msgs::Target_<ContainerAllocator> const> ConstPtr;

}; // struct Target_

typedef ::bin_msgs::Target_<std::allocator<void> > Target;

typedef boost::shared_ptr< ::bin_msgs::Target > TargetPtr;
typedef boost::shared_ptr< ::bin_msgs::Target const> TargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bin_msgs::Target_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bin_msgs::Target_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'bin_msgs': ['/home/sun/ros_ws/src/bin_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bin_msgs::Target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bin_msgs::Target_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bin_msgs::Target_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bin_msgs::Target_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bin_msgs::Target_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bin_msgs::Target_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bin_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b9fa2ab2744d7ffa49bcedc9d894beb";
  }

  static const char* value(const ::bin_msgs::Target_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b9fa2ab2744d7ffULL;
  static const uint64_t static_value2 = 0xa49bcedc9d894bebULL;
};

template<class ContainerAllocator>
struct DataType< ::bin_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bin_msgs/Target";
  }

  static const char* value(const ::bin_msgs::Target_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bin_msgs::Target_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
string type\n\
";
  }

  static const char* value(const ::bin_msgs::Target_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bin_msgs::Target_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Target_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bin_msgs::Target_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bin_msgs::Target_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIN_MSGS_MESSAGE_TARGET_H
